### ISSUE TITLE
Hi, what is going on? FileNotFoundError: [Errno 2] No such file or directory: '../datasets/WN31/EN_DE_15K_V1/pre/kg1_rel_dict'

### ISSUE THREAD

**Issue by daima2017** [cwswork/RPR_RHGT#2]
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/WN31/EN_DE_15K_V1/pre/kg1_rel_dict'

**Comment by cwswork** [comment]
Sorry, some dataset files were not uploaded due to my negligence, which was just uploaded.&nbsp;
If there are any other missing data files, please notify me as soon as possible.


https://www.jianguoyun.com/p/DY8iIAsQ2t_lCBjK3oUEIAA
https://www.jianguoyun.com/p/DWzhBksQ2t_lCBjon78EIAA


Weishan Cai
 
***@***.***

***@***.***
 
School of Computer Science
 
South China Normal University
 
Guangzhou 510631 P.R. China



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwswork/RPR_RHGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 下午5:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cwswork/RPR_RHGT] Hi, what is going on? FileNotFoundError: [Errno 2] No such file or directory: '../datasets/WN31/EN_DE_15K_V1/pre/kg1_rel_dict' (Issue #2)





 
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/WN31/EN_DE_15K_V1/pre/kg1_rel_dict'
